"""Pydantic response/request schemas — re-exports for backward compatibility."""

from .admin import (
    ArtistDeezerIn,
    ArtistFlagOut,
    CrawlLogItem,
    CrawlLogsResponse,
    DeezerArtistHit,
    DeezerGenreLookupResponse,
    EnrichBeatportResponse,
    FetchPlaylistArtworksResponse,
    FlagManualIn,
    LinkDeezerResponse,
    NoDeezerResponse,
    ResetBeatportResponse,
    ResolveIn,
    SetArtistAddResponse,
    SetArtistIn,
    SyncQueued,
    SyncStatus,
    UnclassifiedCountResponse,
)
from .artist import (
    ArtistAliasOut,
    ArtistConnectionComponents,
    ArtistConnectionOut,
    ArtistDetailOut,
    ArtistListItemOut,
    ArtistListOut,
    ArtistListResponse,
    ArtistOut,
    ArtistSetOut,
)
from .auth import GoogleLoginResponse, UserOut
from .catalog import (
    AvisResponse,
    CatalogAvisUpdate,
    CatalogDetailOut,
    CatalogEntryOut,
    CatalogGenreItem,
    CatalogImportIn,
    CatalogImportOut,
    CatalogList,
    PreviewUrlResponse,
    RadarAppearanceOut,
    SameArtistTrackOut,
    SetAppearanceOut,
    SimilarityBlock,
    SimilarityComponents,
    SimilarTrackOut,
)
from .collections import (
    CollectionCreateIn,
    CollectionDetailOut,
    CollectionItemAddIn,
    CollectionItemOut,
    CollectionOut,
)
from .common import ArtistRef, GenreRef, OkResponse, RandomTrackResponse
from .following import (
    ActivityListResponse,
    ArtistActivityOut,
    FollowedArtistOut,
    FollowingListResponse,
    FollowStateResponse,
)
from .genres import (
    GenreArtistItem,
    GenreArtistListResponse,
    GenreDetailResponse,
    GenreListItem,
    GenreListResponse,
    GenreMergeIn,
    GenreMergeResponse,
    GenreNeighborItem,
    GenreNeighborResponse,
    GenrePlaylistItem,
    GenrePlaylistListResponse,
    GenreRenameIn,
    GenreRenameResponse,
    GenreSetItem,
    GenreSetListResponse,
    GenreTrackItem,
    GenreTrackListResponse,
)
from .import_rb import ImportQueuedResponse, ImportStatusResponse
from .opinions import OpinionSetResponse, OpinionUpdate
from .radar import (
    NewCountResponse,
    RadarBatchItem,
    RadarBatchResponse,
    RadarFullList,
    RadarFullOut,
    RadarStateResponse,
    RadarStateUpdate,
    RadarStatus,
    RadarTrackIn,
    RadarTrackOut,
    TrendItem,
    TrendList,
)
from .recommendations import RecommendationItem, RecommendationList
from .search import (
    ExternalSearchItem,
    ExternalSearchResponse,
    SearchItem,
    SearchResponse,
    SearchTotals,
)
from .sets import (
    DJSetDetailOut,
    DJSetList,
    DJSetOut,
    SetArtistDetailOut,
    SetArtistOut,
    SetFlagAttachResponse,
    SetFlagListResponse,
    SetFlagOut,
    SetImportIn,
    SetImportResponse,
    SetListItemOut,
    SetListResponse,
    SetTrackDetailOut,
    SetTrackOut,
    TrackIDSearchResult,
)
from .taxonomy import (
    TaxonomyDepthNode,
    TaxonomyDepthNodeList,
    TaxonomyEdgeNode,
    TaxonomyEdgeNodeList,
    TaxonomyMapping,
    TaxonomyMappingList,
    TaxonomyMappingUpdateResponse,
    TaxonomyNeighborNode,
    TaxonomyNeighborNodeList,
    TaxonomyNode,
    TaxonomyNodeList,
    TaxonomyStats,
)
from .tracks import TrackImport
from .watchlist import (
    CrawlQueuedResponse,
    CrawlStatusResponse,
    FetchArtworkResponse,
    PlaylistTrackOut,
    WatchedEntityBrowseOut,
    WatchedEntityDetailOut,
    WatchedEntityIn,
    WatchedEntityOut,
    WatchlistBrowseResponse,
    WatchlistListResponse,
)

__all__ = [
    # common
    "ArtistRef",
    "GenreRef",
    "OkResponse",
    "RandomTrackResponse",
    # tracks
    "TrackImport",
    # catalog
    "CatalogEntryOut",
    "CatalogAvisUpdate",
    "CatalogList",
    "CatalogDetailOut",
    "CatalogGenreItem",
    "CatalogImportIn",
    "CatalogImportOut",
    "PreviewUrlResponse",
    "AvisResponse",
    "SimilarityComponents",
    "SimilarityBlock",
    "SimilarTrackOut",
    "RadarAppearanceOut",
    "SetAppearanceOut",
    "SameArtistTrackOut",
    # artist
    "ArtistAliasOut",
    "ArtistOut",
    "ArtistListOut",
    "ArtistListItemOut",
    "ArtistListResponse",
    "ArtistConnectionComponents",
    "ArtistConnectionOut",
    "ArtistSetOut",
    "ArtistDetailOut",
    # following
    "FollowStateResponse",
    "FollowedArtistOut",
    "FollowingListResponse",
    "ArtistActivityOut",
    "ActivityListResponse",
    # radar
    "RadarStatus",
    "RadarTrackIn",
    "RadarTrackOut",
    "RadarFullOut",
    "RadarFullList",
    "RadarStateUpdate",
    "RadarBatchItem",
    "TrendItem",
    "TrendList",
    "NewCountResponse",
    "RadarStateResponse",
    "RadarBatchResponse",
    # recommendations
    "RecommendationItem",
    "RecommendationList",
    # sets
    "SetListItemOut",
    "SetListResponse",
    "SetTrackOut",
    "SetArtistOut",
    "DJSetOut",
    "DJSetList",
    "DJSetDetailOut",
    "SetTrackDetailOut",
    "SetArtistDetailOut",
    "SetFlagOut",
    "SetFlagListResponse",
    "SetFlagAttachResponse",
    "SetImportIn",
    "TrackIDSearchResult",
    "SetImportResponse",
    # watchlist
    "WatchedEntityIn",
    "WatchedEntityOut",
    "WatchedEntityBrowseOut",
    "WatchedEntityDetailOut",
    "PlaylistTrackOut",
    "WatchlistListResponse",
    "WatchlistBrowseResponse",
    "CrawlQueuedResponse",
    "CrawlStatusResponse",
    "FetchArtworkResponse",
    # genres
    "GenreRenameIn",
    "GenreMergeIn",
    "GenreListItem",
    "GenreListResponse",
    "GenreDetailResponse",
    "GenreArtistItem",
    "GenreArtistListResponse",
    "GenreSetItem",
    "GenreSetListResponse",
    "GenrePlaylistItem",
    "GenrePlaylistListResponse",
    "GenreTrackItem",
    "GenreTrackListResponse",
    "GenreNeighborItem",
    "GenreNeighborResponse",
    "GenreMergeResponse",
    "GenreRenameResponse",
    # collections
    "CollectionCreateIn",
    "CollectionItemAddIn",
    "CollectionOut",
    "CollectionItemOut",
    "CollectionDetailOut",
    # opinions
    "OpinionUpdate",
    "OpinionSetResponse",
    # admin
    "ArtistFlagOut",
    "SyncQueued",
    "SyncStatus",
    "ResolveIn",
    "ArtistDeezerIn",
    "FlagManualIn",
    "SetArtistIn",
    "DeezerArtistHit",
    "LinkDeezerResponse",
    "NoDeezerResponse",
    "SetArtistAddResponse",
    "ResetBeatportResponse",
    "EnrichBeatportResponse",
    "UnclassifiedCountResponse",
    "DeezerGenreLookupResponse",
    "FetchPlaylistArtworksResponse",
    "CrawlLogItem",
    "CrawlLogsResponse",
    # auth
    "UserOut",
    "GoogleLoginResponse",
    # search
    "SearchItem",
    "SearchTotals",
    "SearchResponse",
    "ExternalSearchItem",
    "ExternalSearchResponse",
    # taxonomy
    "TaxonomyNode",
    "TaxonomyNodeList",
    "TaxonomyEdgeNode",
    "TaxonomyEdgeNodeList",
    "TaxonomyDepthNode",
    "TaxonomyDepthNodeList",
    "TaxonomyNeighborNode",
    "TaxonomyNeighborNodeList",
    "TaxonomyStats",
    "TaxonomyMapping",
    "TaxonomyMappingList",
    "TaxonomyMappingUpdateResponse",
    # import
    "ImportQueuedResponse",
    "ImportStatusResponse",
]
