"""Curated media/non-artist DENYLIST for the set-artist extractor (data module).

PURE data (stdlib + ``workers.artist_names`` folds only) — importable from the
worker, the API and the ops scripts alike (no celery/redis/DB).

ORIGIN — one-shot classification (LLM + web) of the highest-frequency
title-candidate tokens and channels the C13.c extractor was OVER-linking: online
radios, media/magazines, labels, festivals, parties, mix-series and uploader
handles that are NEVER the DJ. Only rows a curator marked DENYLIST are here; KEEP
(real artists) and UNSURE were dropped, and any denylist key that collided with a
KEEP name under the same fold was excluded (invariant #4 — denylisting a real
artist is an irreversible loss, so a real artist always wins).

REFRESH — regenerate ~annually from a fresh prod top-N export (the same curation
pass). This file is baked as LITERALS on purpose: it must be reviewable in git and
must not read any external file at runtime.

Two frozensets, matched with DIFFERENT fold keys to mirror how each consumer keys:

- :data:`MEDIA_TITLE_KEYS` — ``artist_names.space_fold_key(name)`` (punctuation AND
  spaces dropped), unioned into ``set_artist_extract._NOT_ARTIST`` so a title
  candidate whose space-fold equals one of these is rejected. Same key family as
  the hand-written genre/city terms already in ``_NOT_ARTIST``.
- :data:`MEDIA_CHANNEL_KEYS` — the EXACT ``artist_names.punct_fold_key`` of the
  WHOLE cleaned channel (the key ``set_title_meta._fold_tokens`` is built on),
  consulted by ``set_title_meta.is_known_channel``. An EXACT whole-channel key is
  chosen over token containment ON PURPOSE: a media channel is denylisted only when
  the full channel name matches, so a short shared token ("Radio", "FM") can never
  fire on — and silently kill — a real artist's own channel. ``is_known_channel``
  keeps its existing gazetteer containment match on top; this set only EXTENDS it.
"""

MEDIA_TITLE_KEYS = frozenset(
    {
        "#slamradio",
        "6am",
        "ade",
        "afterhoursounds",
        "alaplay",
        "animalia",
        "anjunadeep",
        "archaic",
        "arteconcert",
        "awakenings",
        "balamii",
        "balanceselections",
        "balanceseries",
        "bassiani",
        "bcco",
        "bccomixseries",
        "beatsinspace",
        "behindtheironcurtain",
        "bis",
        "bleep",
        "blooplondonradio",
        "boilerroom",
        "brl",
        "brutalforms",
        "burningman",
        "c",
        "cb",
        "chicago",
        "circoloco",
        "circolocoradio",
        "clandestino",
        "clubberia",
        "cosmovisionrecords",
        "crack",
        "crackmagazine",
        "daisychain",
        "danceanthems",
        "dancetv",
        "darkunderground",
        "datatransmissionradio",
        "deep",
        "deepbreakfast",
        "deepbreakfastseries",
        "defected",
        "defectedrecords",
        "dekmantel",
        "delayed",
        "dgtl",
        "dhafm(deephouseamsterdam",
        "differentsound",
        "digitalnightmusic",
        "digitaltsunami",
        "dimensionsfestival",
        "djmag",
        "djsets4u",
        "dreamchimney",
        "drumcoderadio",
        "drumcomplexed",
        "dsams",
        "duskrecords",
        "eg",
        "egregorecollective",
        "electricshapes",
        "electronicmusicradio",
        "essentialmix",
        "fabric",
        "fact",
        "faderadio",
        "feedersound",
        "flowradioshow",
        "foundationfm",
        "fourfourmagazine",
        "frankfurt",
        "freefromsleep",
        "frenzy",
        "friends",
        "frittofm",
        "fusecast",
        "fuserecords",
        "futuredisco",
        "futurediscoradio",
        "futureintel",
        "gasolineradio",
        "giftofsong",
        "gimic",
        "glitchfestival",
        "glitterbox",
        "glitterboxrecordings",
        "goodroombk",
        "goptun",
        "grainy",
        "groove",
        "groovemagazin",
        "halfisenough",
        "hate",
        "hellostrange",
        "hessleaudio",
        "hkcr",
        "hocast",
        "hocradio",
        "honcho",
        "hor",
        "hosted",
        "hypnoticgroove",
        "ia",
        "id",
        "idj",
        "illegalalienrecords",
        "indarkwetrust",
        "infocus",
        "intercell",
        "inthemood",
        "isburning",
        "it",
        "jackiesmusic",
        "jamiedmusic",
        "janvier",
        "karotteskitchen",
        "katahaifisch",
        "keephush",
        "keinemusik",
        "khidi",
        "kioskradio",
        "komrad",
        "konbiniradio",
        "layer",
        "lesilotselectroniques",
        "levisiteuronline",
        "listentoflow",
        "localselection",
        "looselips",
        "lostinether",
        "loveland",
        "lovelee",
        "lylradio",
        "m1dance",
        "magpie303",
        "mai",
        "maledettadiscoteca",
        "mannyztapez",
        "mantissa",
        "mayanwarrior",
        "melbournedeepcast",
        "meoko",
        "minimallt",
        "mitaminelab",
        "mix",
        "mixed",
        "mixofthe",
        "mnmt",
        "momentodemento",
        "monasterio",
        "monasteriochamber",
        "monument",
        "music",
        "mutantradio",
        "mwtg",
        "natureone",
        "nightclubber",
        "nightclubberro",
        "nocturnalwax",
        "noodsradio",
        "novembre",
        "nts",
        "nyc",
        "o",
        "octobre",
        "oecus",
        "oilcan",
        "openlabradio",
        "operator",
        "opiumclub",
        "outsiders",
        "paeo",
        "phonicarecords",
        "phormix",
        "progscopie",
        "purified",
        "ra",
        "radioradio",
        "radioraheemmilano",
        "radiorudina",
        "radiowebphre",
        "ransomnote",
        "ravetheplanet",
        "raw",
        "rbl",
        "rblmedia",
        "reclaimyourcity",
        "recorded",
        "refugeworldwide",
        "retrospect",
        "rhythmicculture",
        "rinsefm",
        "robotheart",
        "rocketradio",
        "rrfm",
        "rtsfm",
        "saviourgermany",
        "scenenoise",
        "secretdomain",
        "sedubtive",
        "seeksicksound",
        "selador",
        "seladorrecordings",
        "select",
        "selected",
        "series",
        "setoftheday",
        "sexydinosaurfromouterspace",
        "slothboogie",
        "slothboogieguestmix",
        "sonderspur",
        "soundkleckserecords",
        "soundspace",
        "souptonuts",
        "sowhat!radioshow",
        "sowhatradioshow",
        "special",
        "specialguest",
        "spectrumradio",
        "stampthewax",
        "stereoproductions",
        "strangebutdancemusic",
        "studio96",
        "studiobrussel",
        "sunshine",
        "swufm",
        "the",
        "theboomroom",
        "thebunkerny",
        "theclassicmixcdseries",
        "theearlybirdshow",
        "thegardensofbabylon",
        "themuddshow",
        "thentsbreakfastshow",
        "timewarp",
        "to",
        "toxicfamily",
        "transitionradio",
        "transitions",
        "transmissions",
        "trnstnradio",
        "troally",
        "tronic",
        "truancy",
        "truants",
        "trueunderground(truetechno",
        "turnedon",
        "uk",
        "unitedwestream",
        "vault",
        "verknipt",
        "wav",
        "wearevarious",
        "whenwedip",
        "whypeopledance",
        "worldismine",
        "worldwidefm",
        "xlr8r",
        "xoxablend",
        "xoxanyc",
        "youfmradio",
        "zeezout",
    }
)

MEDIA_CHANNEL_KEYS = frozenset(
    {
        "180fact",
        "6am",
        "alaplay",
        "anjunadeep",
        "archaic",
        "arte concert",
        "awakenings",
        "balamii",
        "balance series",
        "bassiani",
        "bcco",
        "beats in space",
        "bleep",
        "bloop london radio",
        "boiler room",
        "c",
        "circoloco",
        "clubberia",
        "crack magazine",
        "daisychain",
        "dance anthems radio show",
        "dance tv",
        "dark underground podcast",
        "data transmission radio",
        "deep breakfast series",
        "defected",
        "dekmantel",
        "delayed",
        "dgtl",
        "differentsound",
        "digital night music",
        "dimensions festival",
        "djsets4u",
        "dream chimney",
        "eg",
        "egregore collective",
        "electric shapes",
        "fabric",
        "fade radio",
        "feeder sound",
        "foundationfm",
        "four four magazine",
        "fritto fm",
        "fuse",
        "future disco",
        "future intel",
        "gasoline radio",
        "gift of song",
        "glitterbox recordings",
        "gop tun",
        "groove magazin",
        "half is enough",
        "hate",
        "hellostrange | secret domain | sedubtive | 20",
        "hkcr",
        "honcho",
        "hor berlin",
        "id",
        "intercell",
        "jamiedmusic",
        "karotteskitchen",
        "katahaifisch",
        "keinemusik",
        "kiosk radio",
        "komrad",
        "konbini radio",
        "listen to flow",
        "loose lips",
        "m1 dance",
        "magpie303",
        "mantissa",
        "meoko",
        "minimallt",
        "mitamine lab",
        "mixcloud nts radio",
        "mixmag",
        "monasterio",
        "monument",
        "mutant radio",
        "mwtg",
        "nocturnal wax",
        "nts friday",
        "nts latest",
        "nts monday",
        "nts thursday",
        "nts tuesday",
        "nts wednesday",
        "oecus",
        "openlab radio",
        "operator",
        "radio raheem milano",
        "radio webphre",
        "ransom note",
        "raw",
        "rblmedia",
        "reclaim your city",
        "refuge worldwide",
        "resident advisor",
        "rinse fm",
        "rinse france",
        "rocket radio",
        "rrfm radio radio",
        "rtsfm",
        "saviourgermany",
        "scenenoise",
        "selador recordings",
        "set of the day",
        "sexy dinosaur from outer space",
        "slothboogie",
        "so what! radioshow",
        "sonderspur podcast | frankfurt",
        "stereo productions",
        "studio brussel",
        "sunshine live electronic music radio",
        "swufm",
        "the boom room",
        "the classic mix cd series",
        "the gardens of babylon",
        "the lot radio",
        "the mudd show",
        "toxic family frankfurt",
        "trnstn radio",
        "troally",
        "trommel",
        "truants",
        "turned on",
        "verknipt",
        "we are various | wav",
        "when we dip",
        "whypeopledance",
        "worldwide fm",
        "xlr8r",
        "youfmradio",
        "zeezout",
    }
)
